name: Extract Secret
on: workflow_dispatch # 允许手动触发

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Encode and Print Secret
        # 将 Secret 转换为 Base64 编码输出，防止被 GitHub 屏蔽为 ***
        run: echo -n "${{ secrets.BACKEND_TOML }}" | base64
