name: Extract Secret
on: workflow_dispatch

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Encode and Print Secret
        # 使用 env 环境变量传递，防止 Secret 中的特殊字符破坏脚本
        env:
          MY_SECRET_VALUE: ${{ secrets.BACKEND_TOML }}
        run: |
          echo -n "$MY_SECRET_VALUE" | base64
